cloud_gallery/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from cloud_gallery import settings
from cloud_gallery.views import SignUpView
from users.views import UserListView

auth_urls = [
    path('', include('django.contrib.auth.urls')),
    path('signup/', SignUpView.as_view(), name='signup')
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(auth_urls)),
    path('', UserListView.as_view(), name='user-list'),
    path('users/', include('users.urls')),
    path('photos/', include('photos.urls')),
] + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photos/urls.py
from django.urls import path

from photos.views import PhotoDeleteView, PhotoUpdateView, PhotoUploadView

app_name = "photos"

urlpatterns = [
    path("upload/", PhotoUploadView.as_view(), name="upload"),
    path("<int:pk>/delete/", PhotoDeleteView.as_view(), name="delete"),
    path("<int:pk>/update/", PhotoUpdateView.as_view(), name="update"),
]

users/urls.py
from django.urls import path

from users.views import UserDetailView, UserPhotosDownloadView

app_name = 'users'

urlpatterns = [
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/download_photos/', UserPhotosDownloadView.as_view(), name='download_photos'),
]

photos/models.py
import os

from django.db import models
from django.utils.timezone import now

from cloud_gallery.settings import AUTH_USER_MODEL


def upload_to_user_directory_with_timestamp(instance, filename):
    ext = filename.split('.')[-1]
    return f'user_{instance.user.id}/{now().strftime("%Y%m%d%H%M%S")}.{ext}'


class Photo(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='photos')
    image = models.ImageField(upload_to=upload_to_user_directory_with_timestamp)
    title = models.CharField(max_length=100, blank=False, null=False)
    description = models.TextField(blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title or f'Photo {self.id}'

    class Meta:
        ordering = ['-uploaded_at']

    def delete(self, *args, **kwargs):
        # Delete from media folder
        if self.image:
            if os.path.isfile(self.image.path):
                os.remove(self.image.path)
        super().delete(*args, **kwargs)

users/models.py
from functools import cached_property

from django.contrib.auth.models import AbstractUser
from django.urls import reverse

from photos.models import Photo


class CustomUser(AbstractUser):

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'pk': self.pk})

    def get_download_photos_url(self):
        return reverse('users:download_photos', kwargs={'pk': self.pk})

    @cached_property
    def last_photo(self) -> Photo:
        return self.photos.first()

cloud_gallery/forms.py
from django.contrib.auth.forms import UserCreationForm

from users.models import CustomUser


class SignUpForm(UserCreationForm):
   class Meta:
      model = CustomUser
      fields = ('username', 'password1', 'password2',)

photos/forms.py
from django import forms

from photos.models import Photo


class PhotoUploadForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ('title', 'description', 'image')

cloud_gallery/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from cloud_gallery.forms import SignUpForm


class SignUpView(CreateView):
    form_class = SignUpForm
    template_name = "registration/signup.html"
    success_url = reverse_lazy("login")

photos/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DeleteView, UpdateView

from photos.forms import PhotoUploadForm
from photos.models import Photo


class PhotoMixin(LoginRequiredMixin):
    model = Photo

    def get_success_url(self):
        return self.request.user.get_absolute_url()


class PhotoUploadView(PhotoMixin, CreateView):
    form_class = PhotoUploadForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class PhotoUpdateView(PhotoMixin, UpdateView):
    fields = ('title', 'description')


class PhotoDeleteView(PhotoMixin, DeleteView):
    def get_queryset(self):
        return Photo.objects.filter(user=self.request.user)

users/views.py
import io
import zipfile

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.views import View
from django.views.generic import DetailView, ListView

from photos.models import Photo
from users.models import CustomUser


class UserListView(LoginRequiredMixin, ListView):
    model = CustomUser
    context_object_name = 'users'

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(photos__isnull=False).distinct()
        return qs

class UserDetailView(LoginRequiredMixin, DetailView):
    model = CustomUser
    context_object_name = 'user'


class UserPhotosDownloadView(LoginRequiredMixin, View):
    # TODO: Implement photo download via Celery for users with many photos
    # Create a Celery task to generate the zip archive
    # Save the zip file to a cloud storage

    def get(self, request, pk):
        owner = get_object_or_404(CustomUser, pk=pk)
        photos = Photo.objects.filter(user=owner)
        if not photos.exists():
            return HttpResponse("User has no photos", content_type="text/plain")

        buffer = io.BytesIO()
        with zipfile.ZipFile(buffer, "w") as zip_file:
            for photo in photos:
                filename = photo.image.name.split("/")[-1]
                zip_file.writestr(filename, photo.image.read())

        buffer.seek(0)
        response = HttpResponse(buffer, content_type="application/zip")
        response["Content-Disposition"] = f'attachment; filename="{owner.username}_photos.zip"'
        return response

photos/templates/photos/photo_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow-lg">
                <div class="card-body text-center">
                    <h4 class="card-title mb-4">Confirm Deletion</h4>
                    <p>Are you sure you want to delete photo?</p>
                    <form method="post">
                        {% csrf_token %}
                        <div class="d-flex justify-content-center gap-3">
                            <button type="submit" class="btn btn-danger">
                                Delete
                            </button>
                            <a href="{{ request.user.get_absolute_url }}" class="btn btn-secondary">
                                Cancel
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

photos/templates/photos/photo_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container py-5">
    <div class="row justify-content-md-center align-items-center">
    <div class="col-6">
       <form method="POST" enctype="multipart/form-data">
       {% csrf_token %}
       {{ form | crispy }}
       <input type="submit" value="Upload" class="btn btn-success">
   </form>
    </div>
  </div>

</div>
{% endblock %}

templates/base.html
{% load bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="en" data-bs-theme="auto" style="overflow-y: scroll">
<head>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>
        {% block title %}
        Cloud Gallery
        {% endblock %}
    </title>
</head>

<body class="d-flex flex-column min-vh-100">

{% block header %}
<header class="p-3 text-bg-dark navbar-dark bg-dark">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a class="navbar-brand" href="{% url 'user-list' %}">CloudGallery</a>
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{{ request.user.get_absolute_url }}" class="nav-link px-2 text-white">My Gallery</a></li>
                <li><a href="{% url 'photos:upload' %}" class="nav-link px-2 text-white">Upload new photo</a></li>
            </ul>
            <div class="text-end">
                <form class="d-flex" method="POST" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button class="btn btn-outline-light" type="submit">Sign-out</button>
                </form>
            </div>
        </div>
    </div>
</header>
{% endblock %}

<main class="flex-fill">
    {% block content %}

    {% endblock %}
</main>

{% block footer %}
<footer class="text-body-secondary py-5 mt-auto">
    <div class="container">
        <p class="float-end mb-1"><a href="#">Back to top</a></p>
        <p class="mb-1">Cloud Gallery is an educational project for learning AWS. </p>
    </div>
</footer>
{% endblock %}
</body>
</html>

users/templates/users/customuser_detail.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}

{% block content %}

<main>
    <div class="album py-5 bg-body-tertiary">
        <div class="container ">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for photo in user.photos.all %}
                    <div class="col">
                    <div class="card shadow-sm h-100">
                        <img src="{{photo.image.url}}" class="card-img-top"  alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{photo.title}}</h5>
                            <p class="card-text">{{photo.description}}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-body-secondary">Uploaded at: {{ photo.uploaded_at|naturaltime }}</small>
                                <div class="btn-group">
                                    <a class="btn btn-sm btn-outline-primary" target="_blank" href="{{ photo.image.url }}" role="button">Open</a>
                                    <a class="btn btn-sm btn-outline-primary" href="{% url 'photos:update' pk=photo.pk %}" role="button">Update</a>
                                    <a class="btn btn-sm btn-outline-primary" target="_blank" href="{{ photo.image.url }}" download role="button">Download</a>
                                    {% if user == request.user %}
                                        <a class="btn btn-sm btn-outline-danger" href="{% url 'photos:delete' pk=photo.pk %}" role="button">Delete</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</main>

{% endblock %}

users/templates/users/customuser_list.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}

{% block content %}

<main>
    <div class="album py-5 bg-body-tertiary">
        <div class="container ">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for user in users %}
                    <div class="col">
                    <div class="card shadow-sm h-100">
                        <img src="{{user.last_photo.image.url}}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{user.username}}'s photos.</h5>
                            <p class="card-text">Number of Photos: {{ user.photos.count }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-body-secondary">Last upload: {{ user.last_photo.uploaded_at|naturaltime }}</small>
                                <div class="btn-group">
                                    <a class="btn btn-sm btn-outline-secondary" href="{{ user.get_absolute_url }}" role="button">View</a>
                                    <a class="btn btn-sm btn-outline-secondary" href="{{ user.get_download_photos_url }}" role="button">Download</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</main>

{% endblock %}